In [1]:
import pandas as pd
dataset = pd.read_csv("50_Startups.csv")

In [2]:
dataset.head(5)

   R&D Spend  Administration  Marketing Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39
3  144372.41       118671.85        383199.62    New York  182901.99
4  142107.34        91391.77        366168.42     Florida  166187.94

In [3]:
dataset = pd.get_dummies(dataset, dtype=int, drop_first = True)

In [4]:
dataset.head(5)

,R&D Spend,Administration,Marketing Spend,Profit,State_Florida,State_New York
0,165349.20,136897.80,471784.10,192261.83,0,1
1,162597.70,151377.59,443898.53,191792.06,0,0
2,153441.51,101145.55,407934.54,191050.39,1,0
3,144372.41,118671.85,383199.62,182901.99,0,1
4,142107.34,91391.77,366168.42,166187.94,1,0

In [5]:
dataset.columns

Index(['R&D Spend', 'Administration', 'Marketing Spend', 'Profit',
       'State_Florida', 'State_New York'],
      dtype='object')

In [9]:
independent = dataset[['R&D Spend', 'Administration', 'Marketing Spend','State_Florida', 'State_New York']]
dependent=dataset[['Profit']]

In [10]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(independent, dependent, test_size=0.3, random_state=0)

In [12]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [14]:
X_train[0]

array([ 1.17644103,  0.84515251,  0.94354978,  2.        , -0.76870611])

In [18]:
import pickle
loaded_model = pickle.load(open("finalized_model_svm.sav",'rb'))

In [19]:
loaded_model.predict([[1234,345,4567,0,0]])

array([256523.61830826])

In [20]:
preinput =sc.transform([[1234,345,4567,0,0]])

C:\Anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(

In [22]:
preinput

array([[-1.46890682, -4.79078955, -1.50309804, -0.5       , -0.76870611]])

In [21]:
loaded_model.predict(preinput)

array([108585.37402915])