In [1]:
import pandas as pd
dataset = pd.read_csv("insurance_pre.csv")

In [2]:
import warnings
warnings.filterwarnings("ignore")

In [3]:
dataset.head(2)

   age     sex    bmi  children smoker     charges
0   19  female  27.90         0    yes  16884.9240
1   18    male  33.77         1     no   1725.5523

In [4]:
dataset = pd.get_dummies(dataset, dtype=int, drop_first=True)

In [5]:
dataset.head(2)

   age    bmi  children     charges  sex_male  smoker_yes
0   19  27.90         0  16884.9240         0           1
1   18  33.77         1   1725.5523         1           0

In [6]:
dataset.columns

Index(['age', 'bmi', 'children', 'charges', 'sex_male', 'smoker_yes'], dtype='object')

In [7]:
independent=dataset[['age', 'bmi', 'children',  'sex_male', 'smoker_yes']]
dependent=dataset[['charges']]

In [9]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(independent, dependent, test_size=0.3, random_state=0)

In [10]:
from sklearn.ensemble import RandomForestRegressor

In [11]:
from sklearn.model_selection import GridSearchCV
param_grid = {'criterion':['squared_error', 'absolute_error', 'friedman_mse', 'poisson'],
              'max_features': ['None','sqrt','log2'],
              'n_estimators':[10,100]}
grid = GridSearchCV(RandomForestRegressor(), param_grid, refit = True, verbose= 3,n_jobs=-1)
grid.fit(X_train, y_train)

Fitting 5 folds for each of 24 candidates, totalling 120 fits

GridSearchCV(estimator=RandomForestRegressor(), n_jobs=-1,
             param_grid={'criterion': ['squared_error', 'absolute_error',
                                       'friedman_mse', 'poisson'],
                         'max_features': ['None', 'sqrt', 'log2'],
                         'n_estimators': [10, 100]},
             verbose=3)

In [12]:
result=grid.cv_results_
print(result)

{'mean_fit_time': array([0.00429101, 0.00549793, 0.09801192, 0.67028394, 0.07539134,
       0.67119141, 0.00235476, 0.00346322, 0.19522905, 1.78577752,
       0.18383989, 1.81601734, 0.00393019, 0.00519547, 0.07579584,
       0.65638084, 0.07748547, 0.65328588, 0.00410004, 0.00287986,
       0.07681804, 0.71918073, 0.08361526, 0.53616977]), 'std_fit_time': array([0.00194593, 0.00201195, 0.00332727, 0.00914786, 0.00240611,
       0.01222105, 0.00120403, 0.00091614, 0.0026632 , 0.02273329,
       0.00812442, 0.04511161, 0.00115529, 0.00056472, 0.00363231,
       0.00511896, 0.00322516, 0.00696579, 0.0013404 , 0.00113954,
       0.00238843, 0.00774715, 0.00343553, 0.11429893]), 'mean_score_time': array([0.        , 0.        , 0.01502981, 0.04666872, 0.01216941,
       0.03955631, 0.        , 0.        , 0.01284513, 0.04038916,
       0.01269755, 0.0382575 , 0.        , 0.        , 0.01164923,
       0.04067082, 0.01329012, 0.03853498, 0.        , 0.        ,
       0.01260014, 0.03693061, 0.01036129, 0.02224154]), 'std_score_time': array([0.        , 0.        , 0.0027843 , 0.00213427, 0.00133818,
       0.00372352, 0.        , 0.        , 0.001878  , 0.00241268,
       0.00103573, 0.00248896, 0.        , 0.        , 0.0011073 ,
       0.00232751, 0.0015609 , 0.00240751, 0.        , 0.        ,
       0.00092071, 0.00327914, 0.00193984, 0.00394565]), 'param_criterion': masked_array(data=['squared_error', 'squared_error', 'squared_error',
                   'squared_error', 'squared_error', 'squared_error',
                   'absolute_error', 'absolute_error', 'absolute_error',
                   'absolute_error', 'absolute_error', 'absolute_error',
                   'friedman_mse', 'friedman_mse', 'friedman_mse',
                   'friedman_mse', 'friedman_mse', 'friedman_mse',
                   'poisson', 'poisson', 'poisson', 'poisson', 'poisson',
                   'poisson'],
             mask=[False, False, False, False, False, False, False, False,
                   False, False, False, False, False, False, False, False,
                   False, False, False, False, False, False, False, False],
       fill_value=np.str_('?'),
            dtype=object), 'param_max_features': masked_array(data=['None', 'None', 'sqrt', 'sqrt', 'log2', 'log2', 'None',
                   'None', 'sqrt', 'sqrt', 'log2', 'log2', 'None', 'None',
                   'sqrt', 'sqrt', 'log2', 'log2', 'None', 'None', 'sqrt',
                   'sqrt', 'log2', 'log2'],
             mask=[False, False, False, False, False, False, False, False,
                   False, False, False, False, False, False, False, False,
                   False, False, False, False, False, False, False, False],
       fill_value=np.str_('?'),
            dtype=object), 'param_n_estimators': masked_array(data=[10, 100, 10, 100, 10, 100, 10, 100, 10, 100, 10, 100,
                   10, 100, 10, 100, 10, 100, 10, 100, 10, 100, 10, 100],
             mask=[False, False, False, False, False, False, False, False,
                   False, False, False, False, False, False, False, False,
                   False, False, False, False, False, False, False, False],
       fill_value=999999), 'params': [{'criterion': 'squared_error', 'max_features': 'None', 'n_estimators': 10}, {'criterion': 'squared_error', 'max_features': 'None', 'n_estimators': 100}, {'criterion': 'squared_error', 'max_features': 'sqrt', 'n_estimators': 10}, {'criterion': 'squared_error', 'max_features': 'sqrt', 'n_estimators': 100}, {'criterion': 'squared_error', 'max_features': 'log2', 'n_estimators': 10}, {'criterion': 'squared_error', 'max_features': 'log2', 'n_estimators': 100}, {'criterion': 'absolute_error', 'max_features': 'None', 'n_estimators': 10}, {'criterion': 'absolute_error', 'max_features': 'None', 'n_estimators': 100}, {'criterion': 'absolute_error', 'max_features': 'sqrt', 'n_estimators': 10}, {'criterion': 'absolute_error', 'max_features': 'sqrt', 'n_estimators': 100}, {'criterion': 'absolute_error', 'max_features': 'log2', 'n_estimators': 10}, {'criterion': 'absolute_error', 'max_features': 'log2', 'n_estimators': 100}, {'criterion': 'friedman_mse', 'max_features': 'None', 'n_estimators': 10}, {'criterion': 'friedman_mse', 'max_features': 'None', 'n_estimators': 100}, {'criterion': 'friedman_mse', 'max_features': 'sqrt', 'n_estimators': 10}, {'criterion': 'friedman_mse', 'max_features': 'sqrt', 'n_estimators': 100}, {'criterion': 'friedman_mse', 'max_features': 'log2', 'n_estimators': 10}, {'criterion': 'friedman_mse', 'max_features': 'log2', 'n_estimators': 100}, {'criterion': 'poisson', 'max_features': 'None', 'n_estimators': 10}, {'criterion': 'poisson', 'max_features': 'None', 'n_estimators': 100}, {'criterion': 'poisson', 'max_features': 'sqrt', 'n_estimators': 10}, {'criterion': 'poisson', 'max_features': 'sqrt', 'n_estimators': 100}, {'criterion': 'poisson', 'max_features': 'log2', 'n_estimators': 10}, {'criterion': 'poisson', 'max_features': 'log2', 'n_estimators': 100}], 'split0_test_score': array([       nan,        nan, 0.86112788, 0.86678742, 0.84867524,
       0.85643112,        nan,        nan, 0.84019938, 0.85381066,
       0.81454135, 0.86193892,        nan,        nan, 0.8454419 ,
       0.86261723, 0.84639728, 0.86824998,        nan,        nan,
       0.84024467, 0.85943627, 0.86924339, 0.85817733]), 'split1_test_score': array([       nan,        nan, 0.75649309, 0.79129767, 0.77175398,
       0.79585378,        nan,        nan, 0.77128357, 0.79615683,
       0.75703778, 0.7927449 ,        nan,        nan, 0.77849862,
       0.79128667, 0.75171241, 0.78279244,        nan,        nan,
       0.78026927, 0.79086173, 0.75588944, 0.78787181]), 'split2_test_score': array([       nan,        nan, 0.81118354, 0.79993661, 0.76676265,
       0.80376394,        nan,        nan, 0.82564742, 0.80565656,
       0.78184018, 0.8129469 ,        nan,        nan, 0.795518  ,
       0.80584086, 0.79847726, 0.80720583,        nan,        nan,
       0.79290022, 0.80697663, 0.7981111 , 0.80789379]), 'split3_test_score': array([       nan,        nan, 0.82334734, 0.82707846, 0.8003931 ,
       0.82830628,        nan,        nan, 0.81130582, 0.82236341,
       0.81005159, 0.83169007,        nan,        nan, 0.81568372,
       0.82931575, 0.78466187, 0.82878225,        nan,        nan,
       0.79976019, 0.82344552, 0.82095871, 0.8249377 ]), 'split4_test_score': array([       nan,        nan, 0.7574619 , 0.77029404, 0.76089952,
       0.77210891,        nan,        nan, 0.74748679, 0.77325662,
       0.75692408, 0.76926889,        nan,        nan, 0.76820013,
       0.77293827, 0.72861162, 0.76260506,        nan,        nan,
       0.75936853, 0.77048394, 0.76286738, 0.768546  ]), 'mean_test_score': array([       nan,        nan, 0.80192275, 0.81107884, 0.7896969 ,
       0.81129281,        nan,        nan, 0.79918459, 0.81024882,
       0.78407899, 0.81371793,        nan,        nan, 0.80066847,
       0.81239975, 0.78197209, 0.80992711,        nan,        nan,
       0.79450858, 0.81024082, 0.80141401, 0.80948533]), 'std_test_score': array([       nan,        nan, 0.04022597, 0.03328146, 0.03246558,
       0.02883522,        nan,        nan, 0.03458482, 0.02695364,
       0.02480387, 0.03182591,        nan,        nan, 0.02757659,
       0.03115746, 0.04048024, 0.03671552,        nan,        nan,
       0.02668159, 0.03020387, 0.04135712, 0.03083956]), 'rank_test_score': array([17, 17,  9,  4, 14,  3, 17, 17, 12,  5, 15,  1, 17, 17, 11,  2, 16,
        7, 17, 17, 13,  6, 10,  8], dtype=int32)}

In [13]:
grid_pred = grid.predict(X_test)

In [14]:
from sklearn.metrics import r2_score
r_score = r2_score(y_test, grid_pred)
print("The R_score value for best paramete {}:".format(grid.best_params_), r_score)

The R_score value for best paramete {'criterion': 'absolute_error', 'max_features': 'log2', 'n_estimators': 100}: 0.8749487204337354

In [15]:
grid.predict([[54,34,2,1,1]])

array([45833.0219263])

In [16]:
table = pd.DataFrame.from_dict(result)

In [17]:
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_criterion,param_max_features,param_n_estimators,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.004291,0.001946,0.000000,0.000000,squared_error,None,10,"{'criterion': 'squared_error', 'max_features':...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,17
1,0.005498,0.002012,0.000000,0.000000,squared_error,None,100,"{'criterion': 'squared_error', 'max_features':...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,17
2,0.098012,0.003327,0.015030,0.002784,squared_error,sqrt,10,"{'criterion': 'squared_error', 'max_features':...",0.861128,0.756493,0.811184,0.823347,0.757462,0.801923,0.040226,9
3,0.670284,0.009148,0.046669,0.002134,squared_error,sqrt,100,"{'criterion': 'squared_error', 'max_features':...",0.866787,0.791298,0.799937,0.827078,0.770294,0.811079,0.033281,4
4,0.075391,0.002406,0.012169,0.001338,squared_error,log2,10,"{'criterion': 'squared_error', 'max_features':...",0.848675,0.771754,0.766763,0.800393,0.760900,0.789697,0.032466,14
5,0.671191,0.012221,0.039556,0.003724,squared_error,log2,100,"{'criterion': 'squared_error', 'max_features':...",0.856431,0.795854,0.803764,0.828306,0.772109,0.811293,0.028835,3
6,0.002355,0.001204,0.000000,0.000000,absolute_error,None,10,"{'criterion': 'absolute_error', 'max_features'...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,17
7,0.003463,0.000916,0.000000,0.000000,absolute_error,None,100,"{'criterion': 'absolute_error', 'max_features'...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,17
8,0.195229,0.002663,0.012845,0.001878,absolute_error,sqrt,10,"{'criterion': 'absolute_error', 'max_features'...",0.840199,0.771284,0.825647,0.811306,0.747487,0.799185,0.034585,12
9,1.785778,0.022733,0.040389,0.002413,absolute_error,sqrt,100,"{'criterion': 'absolute_error', 'max_features'...",0.853811,0.796157,0.805657,0.822363,0.773257,0.810249,0.026954,5
10,0.183840,0.008124,0.012698,0.001036,absolute_error,log2,10,"{'criterion': 'absolute_error', 'max_features'...",0.814541,0.757038,0.781840,0.810052,0.756924,0.784079,0.024804,15
11,1.816017,0.045112,0.038258,0.002489,absolute_error,log2,100,"{'criterion': 'absolute_error', 'max_features'...",0.861939,0.792745,0.812947,0.831690,0.769269,0.813718,0.031826,1
12,0.003930,0.001155,0.000000,0.000000,friedman_mse,None,10,"{'criterion': 'friedman_mse', 'max_features': ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,17
13,0.005195,0.000565,0.000000,0.000000,friedman_mse,None,100,"{'criterion': 'friedman_mse', 'max_features': ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,17
14,0.075796,0.003632,0.011649,0.001107,friedman_mse,sqrt,10,"{'criterion': 'friedman_mse', 'max_features': ...",0.845442,0.778499,0.795518,0.815684,0.768200,0.800668,0.027577,11
15,0.656381,0.005119,0.040671,0.002328,friedman_mse,sqrt,100,"{'criterion': 'friedman_mse', 'max_features': ...",0.862617,0.791287,0.805841,0.829316,0.772938,0.812400,0.031157,2
16,0.077485,0.003225,0.013290,0.001561,friedman_mse,log2,10,"{'criterion': 'friedman_mse', 'max_features': ...",0.846397,0.751712,0.798477,0.784662,0.728612,0.781972,0.040480,16
17,0.653286,0.006966,0.038535,0.002408,friedman_mse,log2,100,"{'criterion': 'friedman_mse', 'max_features': ...",0.868250,0.782792,0.807206,0.828782,0.762605,0.809927,0.036716,7
18,0.004100,0.001340,0.000000,0.000000,poisson,None,10,"{'criterion': 'poisson', 'max_features': 'None...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,17
19,0.002880,0.001140,0.000000,0.000000,poisson,None,100,"{'criterion': 'poisson', 'max_features': 'None...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,17
20,0.076818,0.002388,0.012600,0.000921,poisson,sqrt,10,"{'criterion': 'poisson', 'max_features': 'sqrt...",0.840245,0.780269,0.792900,0.799760,0.759369,0.794509,0.026682,13
21,0.719181,0.007747,0.036931,0.003279,poisson,sqrt,100,"{'criterion': 'poisson', 'max_features': 'sqrt...",0.859436,0.790862,0.806977,0.823446,0.770484,0.810241,0.030204,6
22,0.083615,0.003436,0.010361,0.001940,poisson,log2,10,"{'criterion': 'poisson', 'max_features': 'log2...",0.869243,0.755889,0.798111,0.820959,0.762867,0.801414,0.041357,10
23,0.536170,0.114299,0.022242,0.003946,poisson,log2,100,"{'criterion': 'poisson', 'max_features': 'log2...",0.858177,0.787872,0.807894,0.824938,0.768546,0.809485,0.030840,8