In [1]:
import pandas as pd
dataset = pd.read_csv("insurance_pre.csv")

In [2]:
import warnings
warnings.filterwarnings("ignore")

In [3]:
dataset.head(2)

   age     sex    bmi  children smoker     charges
0   19  female  27.90         0    yes  16884.9240
1   18    male  33.77         1     no   1725.5523

In [4]:
dataset = pd.get_dummies(dataset, dtype=int, drop_first=True)

In [5]:
dataset.head(2)

   age    bmi  children     charges  sex_male  smoker_yes
0   19  27.90         0  16884.9240         0           1
1   18  33.77         1   1725.5523         1           0

In [6]:
dataset.columns

Index(['age', 'bmi', 'children', 'charges', 'sex_male', 'smoker_yes'], dtype='object')

In [7]:
inde=dataset[['age', 'bmi', 'children',  'sex_male', 'smoker_yes']]
dep=dataset[['charges']]

In [8]:
from sklearn.ensemble import RandomForestRegressor

In [10]:
from sklearn.model_selection import GridSearchCV
param_grid = {'criterion':['squared_error', 'absolute_error', 'friedman_mse', 'poisson'],
              'max_features': ['None','sqrt','log2'],
              'n_estimators':[10,100]}
grid = GridSearchCV(RandomForestRegressor(), param_grid, refit = True, verbose= 3,n_jobs=-1)
grid.fit(inde, dep)

Fitting 5 folds for each of 24 candidates, totalling 120 fits

GridSearchCV(estimator=RandomForestRegressor(), n_jobs=-1,
             param_grid={'criterion': ['squared_error', 'absolute_error',
                                       'friedman_mse', 'poisson'],
                         'max_features': ['None', 'sqrt', 'log2'],
                         'n_estimators': [10, 100]},
             verbose=3)

In [11]:
result=grid.cv_results_
print(result)

{'mean_fit_time': array([0.00349073, 0.00609636, 0.13319073, 0.79541917, 0.09117808,
       0.77786512, 0.0043613 , 0.00292473, 0.3036119 , 2.76440659,
       0.27901878, 2.77798867, 0.00321279, 0.00377417, 0.08302588,
       0.74602661, 0.08501186, 0.75902386, 0.00306115, 0.00401187,
       0.09246178, 0.84393601, 0.09365873, 0.77845454]), 'std_fit_time': array([0.00079939, 0.00079928, 0.00424515, 0.02050217, 0.00510804,
       0.00940345, 0.0008704 , 0.00119464, 0.00534193, 0.02919354,
       0.00292257, 0.03631453, 0.00154277, 0.00124453, 0.00472012,
       0.01921763, 0.0058937 , 0.00941333, 0.00122807, 0.00036282,
       0.00508872, 0.01788623, 0.00411279, 0.08443426]), 'mean_score_time': array([0.        , 0.        , 0.01523728, 0.04431086, 0.01070609,
       0.04395351, 0.        , 0.        , 0.01153255, 0.04273977,
       0.0119863 , 0.04110241, 0.        , 0.        , 0.01246152,
       0.04129343, 0.01254559, 0.04337497, 0.        , 0.        ,
       0.01101747, 0.03626161, 0.0114491 , 0.02872066]), 'std_score_time': array([0.        , 0.        , 0.00227664, 0.00204935, 0.00130665,
       0.0020428 , 0.        , 0.        , 0.0015681 , 0.00246641,
       0.00077913, 0.00383175, 0.        , 0.        , 0.00086974,
       0.00239935, 0.00211216, 0.00156076, 0.        , 0.        ,
       0.00194978, 0.00849116, 0.0014739 , 0.0068783 ]), 'param_criterion': masked_array(data=['squared_error', 'squared_error', 'squared_error',
                   'squared_error', 'squared_error', 'squared_error',
                   'absolute_error', 'absolute_error', 'absolute_error',
                   'absolute_error', 'absolute_error', 'absolute_error',
                   'friedman_mse', 'friedman_mse', 'friedman_mse',
                   'friedman_mse', 'friedman_mse', 'friedman_mse',
                   'poisson', 'poisson', 'poisson', 'poisson', 'poisson',
                   'poisson'],
             mask=[False, False, False, False, False, False, False, False,
                   False, False, False, False, False, False, False, False,
                   False, False, False, False, False, False, False, False],
       fill_value=np.str_('?'),
            dtype=object), 'param_max_features': masked_array(data=['None', 'None', 'sqrt', 'sqrt', 'log2', 'log2', 'None',
                   'None', 'sqrt', 'sqrt', 'log2', 'log2', 'None', 'None',
                   'sqrt', 'sqrt', 'log2', 'log2', 'None', 'None', 'sqrt',
                   'sqrt', 'log2', 'log2'],
             mask=[False, False, False, False, False, False, False, False,
                   False, False, False, False, False, False, False, False,
                   False, False, False, False, False, False, False, False],
       fill_value=np.str_('?'),
            dtype=object), 'param_n_estimators': masked_array(data=[10, 100, 10, 100, 10, 100, 10, 100, 10, 100, 10, 100,
                   10, 100, 10, 100, 10, 100, 10, 100, 10, 100, 10, 100],
             mask=[False, False, False, False, False, False, False, False,
                   False, False, False, False, False, False, False, False,
                   False, False, False, False, False, False, False, False],
       fill_value=999999), 'params': [{'criterion': 'squared_error', 'max_features': 'None', 'n_estimators': 10}, {'criterion': 'squared_error', 'max_features': 'None', 'n_estimators': 100}, {'criterion': 'squared_error', 'max_features': 'sqrt', 'n_estimators': 10}, {'criterion': 'squared_error', 'max_features': 'sqrt', 'n_estimators': 100}, {'criterion': 'squared_error', 'max_features': 'log2', 'n_estimators': 10}, {'criterion': 'squared_error', 'max_features': 'log2', 'n_estimators': 100}, {'criterion': 'absolute_error', 'max_features': 'None', 'n_estimators': 10}, {'criterion': 'absolute_error', 'max_features': 'None', 'n_estimators': 100}, {'criterion': 'absolute_error', 'max_features': 'sqrt', 'n_estimators': 10}, {'criterion': 'absolute_error', 'max_features': 'sqrt', 'n_estimators': 100}, {'criterion': 'absolute_error', 'max_features': 'log2', 'n_estimators': 10}, {'criterion': 'absolute_error', 'max_features': 'log2', 'n_estimators': 100}, {'criterion': 'friedman_mse', 'max_features': 'None', 'n_estimators': 10}, {'criterion': 'friedman_mse', 'max_features': 'None', 'n_estimators': 100}, {'criterion': 'friedman_mse', 'max_features': 'sqrt', 'n_estimators': 10}, {'criterion': 'friedman_mse', 'max_features': 'sqrt', 'n_estimators': 100}, {'criterion': 'friedman_mse', 'max_features': 'log2', 'n_estimators': 10}, {'criterion': 'friedman_mse', 'max_features': 'log2', 'n_estimators': 100}, {'criterion': 'poisson', 'max_features': 'None', 'n_estimators': 10}, {'criterion': 'poisson', 'max_features': 'None', 'n_estimators': 100}, {'criterion': 'poisson', 'max_features': 'sqrt', 'n_estimators': 10}, {'criterion': 'poisson', 'max_features': 'sqrt', 'n_estimators': 100}, {'criterion': 'poisson', 'max_features': 'log2', 'n_estimators': 10}, {'criterion': 'poisson', 'max_features': 'log2', 'n_estimators': 100}], 'split0_test_score': array([       nan,        nan, 0.84908729, 0.85877489, 0.82784016,
       0.85756816,        nan,        nan, 0.84742863, 0.85379246,
       0.85165998, 0.855147  ,        nan,        nan, 0.8446679 ,
       0.85617636, 0.84201957, 0.85749063,        nan,        nan,
       0.84884266, 0.8589606 , 0.83669971, 0.86064536]), 'split1_test_score': array([       nan,        nan, 0.76932975, 0.7780976 , 0.75688986,
       0.77851439,        nan,        nan, 0.7662304 , 0.77984189,
       0.76246953, 0.77956454,        nan,        nan, 0.75895643,
       0.78006956, 0.76736367, 0.77965679,        nan,        nan,
       0.77150659, 0.78147215, 0.75634426, 0.77537198]), 'split2_test_score': array([       nan,        nan, 0.84125594, 0.86235006, 0.83312107,
       0.85656875,        nan,        nan, 0.84307982, 0.85638809,
       0.8294928 , 0.85590253,        nan,        nan, 0.85398066,
       0.85436375, 0.85383117, 0.86008842,        nan,        nan,
       0.8595677 , 0.86100049, 0.85549649, 0.8620645 ]), 'split3_test_score': array([       nan,        nan, 0.82757004, 0.82767511, 0.80498768,
       0.83088646,        nan,        nan, 0.82382881, 0.8259425 ,
       0.80464383, 0.82719463,        nan,        nan, 0.82324747,
       0.82783816, 0.8134645 , 0.82451528,        nan,        nan,
       0.81008521, 0.82600004, 0.81636321, 0.83087767]), 'split4_test_score': array([       nan,        nan, 0.83250414, 0.84266433, 0.81761913,
       0.83919212,        nan,        nan, 0.79094765, 0.84718183,
       0.82484836, 0.84080975,        nan,        nan, 0.82737874,
       0.84187079, 0.82136691, 0.84526752,        nan,        nan,
       0.82259147, 0.83860601, 0.82589816, 0.83951918]), 'mean_test_score': array([       nan,        nan, 0.82394943, 0.8339124 , 0.80809158,
       0.83254597,        nan,        nan, 0.81430306, 0.83262936,
       0.8146229 , 0.83172369,        nan,        nan, 0.82164624,
       0.83206372, 0.81960916, 0.83340373,        nan,        nan,
       0.82251873, 0.83320786, 0.81816037, 0.83369574]), 'std_test_score': array([       nan,        nan, 0.02828791, 0.03052093, 0.02734413,
       0.02887747,        nan,        nan, 0.0312173 , 0.02847932,
       0.03005653, 0.02813153,        nan,        nan, 0.03328949,
       0.02791465, 0.02981211, 0.02966728,        nan,        nan,
       0.03105611, 0.02895966, 0.03353216, 0.0315423 ]), 'rank_test_score': array([17, 17,  9,  1, 16,  6, 17, 17, 15,  5, 14,  8, 17, 17, 11,  7, 12,
        3, 17, 17, 10,  4, 13,  2], dtype=int32)}

In [12]:
print("The best parameter is {}:".format(grid.best_params_))

The best parameter is {'criterion': 'squared_error', 'max_features': 'sqrt', 'n_estimators': 100}:

In [13]:
grid.predict([[54,34,2,1,1]])

array([43794.928268])

In [14]:
table = pd.DataFrame.from_dict(result)

In [15]:
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_criterion,param_max_features,param_n_estimators,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.003491,0.000799,0.000000,0.000000,squared_error,None,10,"{'criterion': 'squared_error', 'max_features':...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,17
1,0.006096,0.000799,0.000000,0.000000,squared_error,None,100,"{'criterion': 'squared_error', 'max_features':...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,17
2,0.133191,0.004245,0.015237,0.002277,squared_error,sqrt,10,"{'criterion': 'squared_error', 'max_features':...",0.849087,0.769330,0.841256,0.827570,0.832504,0.823949,0.028288,9
3,0.795419,0.020502,0.044311,0.002049,squared_error,sqrt,100,"{'criterion': 'squared_error', 'max_features':...",0.858775,0.778098,0.862350,0.827675,0.842664,0.833912,0.030521,1
4,0.091178,0.005108,0.010706,0.001307,squared_error,log2,10,"{'criterion': 'squared_error', 'max_features':...",0.827840,0.756890,0.833121,0.804988,0.817619,0.808092,0.027344,16
5,0.777865,0.009403,0.043954,0.002043,squared_error,log2,100,"{'criterion': 'squared_error', 'max_features':...",0.857568,0.778514,0.856569,0.830886,0.839192,0.832546,0.028877,6
6,0.004361,0.000870,0.000000,0.000000,absolute_error,None,10,"{'criterion': 'absolute_error', 'max_features'...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,17
7,0.002925,0.001195,0.000000,0.000000,absolute_error,None,100,"{'criterion': 'absolute_error', 'max_features'...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,17
8,0.303612,0.005342,0.011533,0.001568,absolute_error,sqrt,10,"{'criterion': 'absolute_error', 'max_features'...",0.847429,0.766230,0.843080,0.823829,0.790948,0.814303,0.031217,15
9,2.764407,0.029194,0.042740,0.002466,absolute_error,sqrt,100,"{'criterion': 'absolute_error', 'max_features'...",0.853792,0.779842,0.856388,0.825943,0.847182,0.832629,0.028479,5
10,0.279019,0.002923,0.011986,0.000779,absolute_error,log2,10,"{'criterion': 'absolute_error', 'max_features'...",0.851660,0.762470,0.829493,0.804644,0.824848,0.814623,0.030057,14
11,2.777989,0.036315,0.041102,0.003832,absolute_error,log2,100,"{'criterion': 'absolute_error', 'max_features'...",0.855147,0.779565,0.855903,0.827195,0.840810,0.831724,0.028132,8
12,0.003213,0.001543,0.000000,0.000000,friedman_mse,None,10,"{'criterion': 'friedman_mse', 'max_features': ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,17
13,0.003774,0.001245,0.000000,0.000000,friedman_mse,None,100,"{'criterion': 'friedman_mse', 'max_features': ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,17
14,0.083026,0.004720,0.012462,0.000870,friedman_mse,sqrt,10,"{'criterion': 'friedman_mse', 'max_features': ...",0.844668,0.758956,0.853981,0.823247,0.827379,0.821646,0.033289,11
15,0.746027,0.019218,0.041293,0.002399,friedman_mse,sqrt,100,"{'criterion': 'friedman_mse', 'max_features': ...",0.856176,0.780070,0.854364,0.827838,0.841871,0.832064,0.027915,7
16,0.085012,0.005894,0.012546,0.002112,friedman_mse,log2,10,"{'criterion': 'friedman_mse', 'max_features': ...",0.842020,0.767364,0.853831,0.813464,0.821367,0.819609,0.029812,12
17,0.759024,0.009413,0.043375,0.001561,friedman_mse,log2,100,"{'criterion': 'friedman_mse', 'max_features': ...",0.857491,0.779657,0.860088,0.824515,0.845268,0.833404,0.029667,3
18,0.003061,0.001228,0.000000,0.000000,poisson,None,10,"{'criterion': 'poisson', 'max_features': 'None...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,17
19,0.004012,0.000363,0.000000,0.000000,poisson,None,100,"{'criterion': 'poisson', 'max_features': 'None...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,17
20,0.092462,0.005089,0.011017,0.001950,poisson,sqrt,10,"{'criterion': 'poisson', 'max_features': 'sqrt...",0.848843,0.771507,0.859568,0.810085,0.822591,0.822519,0.031056,10
21,0.843936,0.017886,0.036262,0.008491,poisson,sqrt,100,"{'criterion': 'poisson', 'max_features': 'sqrt...",0.858961,0.781472,0.861000,0.826000,0.838606,0.833208,0.028960,4
22,0.093659,0.004113,0.011449,0.001474,poisson,log2,10,"{'criterion': 'poisson', 'max_features': 'log2...",0.836700,0.756344,0.855496,0.816363,0.825898,0.818160,0.033532,13
23,0.778455,0.084434,0.028721,0.006878,poisson,log2,100,"{'criterion': 'poisson', 'max_features': 'log2...",0.860645,0.775372,0.862064,0.830878,0.839519,0.833696,0.031542,2