In [1]:
import pandas as pd
dataset = pd.read_csv("insurance_pre.csv")

In [2]:
import warnings
warnings.filterwarnings("ignore")

In [3]:
dataset.head(2)

   age     sex    bmi  children smoker     charges
0   19  female  27.90         0    yes  16884.9240
1   18    male  33.77         1     no   1725.5523

In [4]:
dataset = pd.get_dummies(dataset, dtype=int, drop_first=True)

In [5]:
dataset.head(2)

   age    bmi  children     charges  sex_male  smoker_yes
0   19  27.90         0  16884.9240         0           1
1   18  33.77         1   1725.5523         1           0

In [6]:
dataset.columns

Index(['age', 'bmi', 'children', 'charges', 'sex_male', 'smoker_yes'], dtype='object')

In [7]:
independent=dataset[['age', 'bmi', 'children',  'sex_male', 'smoker_yes']]
dependent=dataset[['charges']]

In [9]:
from sklearn.model_selection import GridSearchCV
from sklearn.tree import DecisionTreeRegressor
param_grid = {'criterion':['mse','mae','friedman_mse'],'max_features': ['auto','sqrt','log2'],
                'splitter':['best','random']}
grid = GridSearchCV(DecisionTreeRegressor(), param_grid, refit=True, verbose=3, n_jobs=-1)
grid.fit(independent, dependent)

Fitting 5 folds for each of 18 candidates, totalling 90 fits

GridSearchCV(estimator=DecisionTreeRegressor(), n_jobs=-1,
             param_grid={'criterion': ['mse', 'mae', 'friedman_mse'],
                         'max_features': ['auto', 'sqrt', 'log2'],
                         'splitter': ['best', 'random']},
             verbose=3)

In [10]:
result=grid.cv_results_
print(result)

{'mean_fit_time': array([0.00669408, 0.00416651, 0.00532475, 0.00370307, 0.0027194 ,
       0.00230236, 0.00560575, 0.00455451, 0.00320249, 0.00264988,
       0.00351   , 0.00262175, 0.00209279, 0.00244236, 0.01495652,
       0.01323743, 0.01437726, 0.00855513]), 'std_fit_time': array([0.00166025, 0.00141147, 0.002043  , 0.00165223, 0.00069221,
       0.00056808, 0.00109113, 0.00114554, 0.00090379, 0.00073277,
       0.00060256, 0.00038612, 0.00074066, 0.00094733, 0.00182319,
       0.00308536, 0.00133124, 0.00116941]), 'mean_score_time': array([0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.00869646,
       0.00585227, 0.00665979, 0.00470295]), 'std_score_time': array([0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.00165362,
       0.00062754, 0.0007755 , 0.00107618]), 'param_criterion': masked_array(data=['mse', 'mse', 'mse', 'mse', 'mse', 'mse', 'mae', 'mae',
                   'mae', 'mae', 'mae', 'mae', 'friedman_mse',
                   'friedman_mse', 'friedman_mse', 'friedman_mse',
                   'friedman_mse', 'friedman_mse'],
             mask=[False, False, False, False, False, False, False, False,
                   False, False, False, False, False, False, False, False,
                   False, False],
       fill_value=np.str_('?'),
            dtype=object), 'param_max_features': masked_array(data=['auto', 'auto', 'sqrt', 'sqrt', 'log2', 'log2', 'auto',
                   'auto', 'sqrt', 'sqrt', 'log2', 'log2', 'auto', 'auto',
                   'sqrt', 'sqrt', 'log2', 'log2'],
             mask=[False, False, False, False, False, False, False, False,
                   False, False, False, False, False, False, False, False,
                   False, False],
       fill_value=np.str_('?'),
            dtype=object), 'param_splitter': masked_array(data=['best', 'random', 'best', 'random', 'best', 'random',
                   'best', 'random', 'best', 'random', 'best', 'random',
                   'best', 'random', 'best', 'random', 'best', 'random'],
             mask=[False, False, False, False, False, False, False, False,
                   False, False, False, False, False, False, False, False,
                   False, False],
       fill_value=np.str_('?'),
            dtype=object), 'params': [{'criterion': 'mse', 'max_features': 'auto', 'splitter': 'best'}, {'criterion': 'mse', 'max_features': 'auto', 'splitter': 'random'}, {'criterion': 'mse', 'max_features': 'sqrt', 'splitter': 'best'}, {'criterion': 'mse', 'max_features': 'sqrt', 'splitter': 'random'}, {'criterion': 'mse', 'max_features': 'log2', 'splitter': 'best'}, {'criterion': 'mse', 'max_features': 'log2', 'splitter': 'random'}, {'criterion': 'mae', 'max_features': 'auto', 'splitter': 'best'}, {'criterion': 'mae', 'max_features': 'auto', 'splitter': 'random'}, {'criterion': 'mae', 'max_features': 'sqrt', 'splitter': 'best'}, {'criterion': 'mae', 'max_features': 'sqrt', 'splitter': 'random'}, {'criterion': 'mae', 'max_features': 'log2', 'splitter': 'best'}, {'criterion': 'mae', 'max_features': 'log2', 'splitter': 'random'}, {'criterion': 'friedman_mse', 'max_features': 'auto', 'splitter': 'best'}, {'criterion': 'friedman_mse', 'max_features': 'auto', 'splitter': 'random'}, {'criterion': 'friedman_mse', 'max_features': 'sqrt', 'splitter': 'best'}, {'criterion': 'friedman_mse', 'max_features': 'sqrt', 'splitter': 'random'}, {'criterion': 'friedman_mse', 'max_features': 'log2', 'splitter': 'best'}, {'criterion': 'friedman_mse', 'max_features': 'log2', 'splitter': 'random'}], 'split0_test_score': array([       nan,        nan,        nan,        nan,        nan,
              nan,        nan,        nan,        nan,        nan,
              nan,        nan,        nan,        nan, 0.73548981,
       0.68733084, 0.74770992, 0.68717182]), 'split1_test_score': array([       nan,        nan,        nan,        nan,        nan,
              nan,        nan,        nan,        nan,        nan,
              nan,        nan,        nan,        nan, 0.64287045,
       0.58227317, 0.59450447, 0.60332567]), 'split2_test_score': array([       nan,        nan,        nan,        nan,        nan,
              nan,        nan,        nan,        nan,        nan,
              nan,        nan,        nan,        nan, 0.66207201,
       0.7179113 , 0.79250625, 0.77032305]), 'split3_test_score': array([       nan,        nan,        nan,        nan,        nan,
              nan,        nan,        nan,        nan,        nan,
              nan,        nan,        nan,        nan, 0.6634338 ,
       0.67557579, 0.6671266 , 0.65332024]), 'split4_test_score': array([       nan,        nan,        nan,        nan,        nan,
              nan,        nan,        nan,        nan,        nan,
              nan,        nan,        nan,        nan, 0.73669229,
       0.67128398, 0.64938949, 0.62053463]), 'mean_test_score': array([       nan,        nan,        nan,        nan,        nan,
              nan,        nan,        nan,        nan,        nan,
              nan,        nan,        nan,        nan, 0.68811167,
       0.66687502, 0.69024735, 0.66693508]), 'std_test_score': array([       nan,        nan,        nan,        nan,        nan,
              nan,        nan,        nan,        nan,        nan,
              nan,        nan,        nan,        nan, 0.03984619,
       0.04533378, 0.07089353, 0.05913226]), 'rank_test_score': array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 2, 4, 1, 3], dtype=int32)}

In [11]:
print("The best parameter is {}:".format(grid.best_params_))

The best parameter is {'criterion': 'friedman_mse', 'max_features': 'log2', 'splitter': 'best'}:

In [12]:
grid.predict([[54,34,2,1,1]])

array([43813.8661])

In [13]:
table = pd.DataFrame.from_dict(result)

In [14]:
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_criterion,param_max_features,param_splitter,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.006694,0.001660,0.000000,0.000000,mse,auto,best,"{'criterion': 'mse', 'max_features': 'auto', '...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,5
1,0.004167,0.001411,0.000000,0.000000,mse,auto,random,"{'criterion': 'mse', 'max_features': 'auto', '...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,5
2,0.005325,0.002043,0.000000,0.000000,mse,sqrt,best,"{'criterion': 'mse', 'max_features': 'sqrt', '...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,5
3,0.003703,0.001652,0.000000,0.000000,mse,sqrt,random,"{'criterion': 'mse', 'max_features': 'sqrt', '...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,5
4,0.002719,0.000692,0.000000,0.000000,mse,log2,best,"{'criterion': 'mse', 'max_features': 'log2', '...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,5
5,0.002302,0.000568,0.000000,0.000000,mse,log2,random,"{'criterion': 'mse', 'max_features': 'log2', '...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,5
6,0.005606,0.001091,0.000000,0.000000,mae,auto,best,"{'criterion': 'mae', 'max_features': 'auto', '...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,5
7,0.004555,0.001146,0.000000,0.000000,mae,auto,random,"{'criterion': 'mae', 'max_features': 'auto', '...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,5
8,0.003202,0.000904,0.000000,0.000000,mae,sqrt,best,"{'criterion': 'mae', 'max_features': 'sqrt', '...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,5
9,0.002650,0.000733,0.000000,0.000000,mae,sqrt,random,"{'criterion': 'mae', 'max_features': 'sqrt', '...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,5
10,0.003510,0.000603,0.000000,0.000000,mae,log2,best,"{'criterion': 'mae', 'max_features': 'log2', '...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,5
11,0.002622,0.000386,0.000000,0.000000,mae,log2,random,"{'criterion': 'mae', 'max_features': 'log2', '...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,5
12,0.002093,0.000741,0.000000,0.000000,friedman_mse,auto,best,"{'criterion': 'friedman_mse', 'max_features': ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,5
13,0.002442,0.000947,0.000000,0.000000,friedman_mse,auto,random,"{'criterion': 'friedman_mse', 'max_features': ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,5
14,0.014957,0.001823,0.008696,0.001654,friedman_mse,sqrt,best,"{'criterion': 'friedman_mse', 'max_features': ...",0.735490,0.642870,0.662072,0.663434,0.736692,0.688112,0.039846,2
15,0.013237,0.003085,0.005852,0.000628,friedman_mse,sqrt,random,"{'criterion': 'friedman_mse', 'max_features': ...",0.687331,0.582273,0.717911,0.675576,0.671284,0.666875,0.045334,4
16,0.014377,0.001331,0.006660,0.000775,friedman_mse,log2,best,"{'criterion': 'friedman_mse', 'max_features': ...",0.747710,0.594504,0.792506,0.667127,0.649389,0.690247,0.070894,1
17,0.008555,0.001169,0.004703,0.001076,friedman_mse,log2,random,"{'criterion': 'friedman_mse', 'max_features': ...",0.687172,0.603326,0.770323,0.653320,0.620535,0.666935,0.059132,3