In [1]:
import pandas as pd
dataset = pd.read_csv("insurance_pre.csv")

In [2]:
dataset.head(2)

   age     sex    bmi  children smoker     charges
0   19  female  27.90         0    yes  16884.9240
1   18    male  33.77         1     no   1725.5523

In [3]:
dataset = pd.get_dummies(dataset, dtype=int, drop_first=True)

In [4]:
dataset.head(2)

   age    bmi  children     charges  sex_male  smoker_yes
0   19  27.90         0  16884.9240         0           1
1   18  33.77         1   1725.5523         1           0

In [5]:
dataset.columns

Index(['age', 'bmi', 'children', 'charges', 'sex_male', 'smoker_yes'], dtype='object')

In [6]:
independent=dataset[['age', 'bmi', 'children',  'sex_male', 'smoker_yes']]
dependent=dataset[['charges']]

In [7]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(independent, dependent, test_size=0.3, random_state=0)

In [8]:
from sklearn.model_selection import GridSearchCV
from sklearn.svm import SVR
param_grid = {'kernel':['rbf','sigmoid','linear'], 
              'C':[10,100,1000,2000,3000], 'gamma':['auto','scale']}
grid = GridSearchCV(SVR(), param_grid, refit=True, verbose=3, n_jobs=-1)
grid.fit(X_train, y_train)

Fitting 5 folds for each of 30 candidates, totalling 150 fits

C:\Anaconda3\Lib\site-packages\sklearn\utils\validation.py:1406: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

GridSearchCV(estimator=SVR(), n_jobs=-1,
             param_grid={'C': [10, 100, 1000, 2000, 3000],
                         'gamma': ['auto', 'scale'],
                         'kernel': ['rbf', 'sigmoid', 'linear']},
             verbose=3)

In [9]:
result=grid.cv_results_
print(result)

{'mean_fit_time': array([0.16029463, 0.0885005 , 0.1263773 , 0.12415347, 0.13677745,
       0.11246939, 0.16297817, 0.08715672, 0.21018734, 0.11396971,
       0.13335547, 0.21665077, 0.23301663, 0.07916703, 0.74705515,
       0.13344984, 0.13745766, 0.7631794 , 0.28449888, 0.08363752,
       1.3140152 , 0.14446092, 0.13889837, 1.31593914, 0.36042714,
       0.0871346 , 2.50963678, 0.14465756, 0.14476309, 2.1419908 ]), 'std_fit_time': array([0.02149068, 0.00582296, 0.00826791, 0.00673817, 0.00286889,
       0.00668892, 0.01250297, 0.00767124, 0.04272221, 0.00461038,
       0.00444631, 0.04459102, 0.00827138, 0.01016463, 0.07573303,
       0.00509679, 0.00646352, 0.06612537, 0.01763372, 0.00294792,
       0.14966614, 0.00935623, 0.00306827, 0.16027572, 0.04362094,
       0.00532796, 1.05985596, 0.00369198, 0.00492222, 0.92565609]), 'mean_score_time': array([0.05114484, 0.02352128, 0.02363911, 0.04859872, 0.03313761,
       0.01742239, 0.04481616, 0.01955223, 0.01581163, 0.0478488 ,
       0.03281937, 0.01885376, 0.04935908, 0.02052035, 0.02100105,
       0.05158186, 0.03143725, 0.01860299, 0.05149441, 0.01959786,
       0.01868277, 0.04850683, 0.03218122, 0.01948981, 0.0517776 ,
       0.02084823, 0.01638422, 0.04997835, 0.0361342 , 0.01116786]), 'std_score_time': array([0.00677621, 0.00442381, 0.00218652, 0.00352612, 0.0029808 ,
       0.00284067, 0.00221629, 0.00193494, 0.00110104, 0.00569082,
       0.0008572 , 0.00125581, 0.00291825, 0.002123  , 0.00292634,
       0.00136185, 0.00151705, 0.00237446, 0.00261927, 0.00128962,
       0.00104505, 0.00496391, 0.00121254, 0.00115846, 0.00270477,
       0.0023212 , 0.00463316, 0.00368278, 0.0031853 , 0.00327706]), 'param_C': masked_array(data=[10, 10, 10, 10, 10, 10, 100, 100, 100, 100, 100, 100,
                   1000, 1000, 1000, 1000, 1000, 1000, 2000, 2000, 2000,
                   2000, 2000, 2000, 3000, 3000, 3000, 3000, 3000, 3000],
             mask=[False, False, False, False, False, False, False, False,
                   False, False, False, False, False, False, False, False,
                   False, False, False, False, False, False, False, False,
                   False, False, False, False, False, False],
       fill_value=999999), 'param_gamma': masked_array(data=['auto', 'auto', 'auto', 'scale', 'scale', 'scale',
                   'auto', 'auto', 'auto', 'scale', 'scale', 'scale',
                   'auto', 'auto', 'auto', 'scale', 'scale', 'scale',
                   'auto', 'auto', 'auto', 'scale', 'scale', 'scale',
                   'auto', 'auto', 'auto', 'scale', 'scale', 'scale'],
             mask=[False, False, False, False, False, False, False, False,
                   False, False, False, False, False, False, False, False,
                   False, False, False, False, False, False, False, False,
                   False, False, False, False, False, False],
       fill_value=np.str_('?'),
            dtype=object), 'param_kernel': masked_array(data=['rbf', 'sigmoid', 'linear', 'rbf', 'sigmoid', 'linear',
                   'rbf', 'sigmoid', 'linear', 'rbf', 'sigmoid', 'linear',
                   'rbf', 'sigmoid', 'linear', 'rbf', 'sigmoid', 'linear',
                   'rbf', 'sigmoid', 'linear', 'rbf', 'sigmoid', 'linear',
                   'rbf', 'sigmoid', 'linear', 'rbf', 'sigmoid', 'linear'],
             mask=[False, False, False, False, False, False, False, False,
                   False, False, False, False, False, False, False, False,
                   False, False, False, False, False, False, False, False,
                   False, False, False, False, False, False],
       fill_value=np.str_('?'),
            dtype=object), 'params': [{'C': 10, 'gamma': 'auto', 'kernel': 'rbf'}, {'C': 10, 'gamma': 'auto', 'kernel': 'sigmoid'}, {'C': 10, 'gamma': 'auto', 'kernel': 'linear'}, {'C': 10, 'gamma': 'scale', 'kernel': 'rbf'}, {'C': 10, 'gamma': 'scale', 'kernel': 'sigmoid'}, {'C': 10, 'gamma': 'scale', 'kernel': 'linear'}, {'C': 100, 'gamma': 'auto', 'kernel': 'rbf'}, {'C': 100, 'gamma': 'auto', 'kernel': 'sigmoid'}, {'C': 100, 'gamma': 'auto', 'kernel': 'linear'}, {'C': 100, 'gamma': 'scale', 'kernel': 'rbf'}, {'C': 100, 'gamma': 'scale', 'kernel': 'sigmoid'}, {'C': 100, 'gamma': 'scale', 'kernel': 'linear'}, {'C': 1000, 'gamma': 'auto', 'kernel': 'rbf'}, {'C': 1000, 'gamma': 'auto', 'kernel': 'sigmoid'}, {'C': 1000, 'gamma': 'auto', 'kernel': 'linear'}, {'C': 1000, 'gamma': 'scale', 'kernel': 'rbf'}, {'C': 1000, 'gamma': 'scale', 'kernel': 'sigmoid'}, {'C': 1000, 'gamma': 'scale', 'kernel': 'linear'}, {'C': 2000, 'gamma': 'auto', 'kernel': 'rbf'}, {'C': 2000, 'gamma': 'auto', 'kernel': 'sigmoid'}, {'C': 2000, 'gamma': 'auto', 'kernel': 'linear'}, {'C': 2000, 'gamma': 'scale', 'kernel': 'rbf'}, {'C': 2000, 'gamma': 'scale', 'kernel': 'sigmoid'}, {'C': 2000, 'gamma': 'scale', 'kernel': 'linear'}, {'C': 3000, 'gamma': 'auto', 'kernel': 'rbf'}, {'C': 3000, 'gamma': 'auto', 'kernel': 'sigmoid'}, {'C': 3000, 'gamma': 'auto', 'kernel': 'linear'}, {'C': 3000, 'gamma': 'scale', 'kernel': 'rbf'}, {'C': 3000, 'gamma': 'scale', 'kernel': 'sigmoid'}, {'C': 3000, 'gamma': 'scale', 'kernel': 'linear'}], 'split0_test_score': array([-0.04189924, -0.04163422, -0.09984888, -0.04547724, -0.04287667,
       -0.09984888, -0.04010704, -0.04163422,  0.47779496, -0.15854611,
       -0.05956133,  0.47779496, -0.06443401, -0.04163422,  0.59228756,
       -0.19142177, -1.14129511,  0.59228756, -0.04147286, -0.04163422,
        0.60033992, -0.18813775, -4.20469931,  0.60033992, -0.01083794,
       -0.04163422,  0.60028152, -0.1822674 , -9.34781977,  0.60028152]), 'split1_test_score': array([ -0.03593094,  -0.03807681,   0.10949779,  -0.01333561,
        -0.03951154,   0.10949779,  -0.02097171,  -0.03807681,
         0.58229243,   0.01377495,  -0.06348023,   0.58229243,
         0.04116893,  -0.03807681,   0.66360712,   0.02196241,
        -1.26970255,   0.66360712,   0.08695577,  -0.03807681,
         0.66445351,   0.02975765,  -4.63989836,   0.66445351,
         0.12365005,  -0.03807681,   0.60052797,   0.03858762,
       -10.01565428,   0.60052797]), 'split2_test_score': array([-0.14715112, -0.14867375, -0.1361956 , -0.1517906 , -0.15015362,
       -0.1361956 , -0.14068305, -0.14867375,  0.43207877, -0.24312713,
       -0.15536761,  0.43207877, -0.17362708, -0.14867375,  0.55934717,
       -0.24659026, -1.07468842,  0.55934717, -0.14358292, -0.14867375,
        0.56469282, -0.23742525, -3.60043109,  0.56469282, -0.11171042,
       -0.14867375,  0.57117456, -0.22806225, -7.89669412,  0.57117456]), 'split3_test_score': array([-0.13998707, -0.13869767, -0.14138099, -0.15196699, -0.13849233,
       -0.14138099, -0.13793147, -0.13869767,  0.45898313, -0.25451996,
       -0.15275665,  0.45898313, -0.16239535, -0.13869767,  0.58263587,
       -0.26481333, -1.22198187,  0.58263587, -0.12967462, -0.13869767,
        0.61869194, -0.25676001, -4.26557528,  0.61869194, -0.08970095,
       -0.13869767,  0.56294593, -0.24591476, -9.54893246,  0.56294593]), 'split4_test_score': array([-0.14220569, -0.1421374 , -0.07543177, -0.13944758, -0.14339556,
       -0.07543177, -0.13374936, -0.1421374 ,  0.43951071, -0.16678165,
       -0.16011487,  0.43951071, -0.13137521, -0.1421374 ,  0.55884944,
       -0.17493537, -1.15463399,  0.55884944, -0.10618635, -0.1421374 ,
        0.56356668, -0.16870073, -3.61237517,  0.56356668, -0.07493154,
       -0.1421374 ,  0.56576592, -0.16187962, -7.66441191,  0.56576592]), 'mean_test_score': array([-0.10143481, -0.10184397, -0.06867189, -0.1004036 , -0.10288594,
       -0.06867189, -0.09468853, -0.10184397,  0.478132  , -0.16183998,
       -0.11825614,  0.478132  , -0.09813254, -0.10184397,  0.59134543,
       -0.17115967, -1.17246039,  0.59134543, -0.0667922 , -0.10184397,
        0.60234898, -0.16425322, -4.06459584,  0.60234898, -0.03270616,
       -0.10184397,  0.58013918, -0.15590729, -8.89470251,  0.58013918]), 'std_test_score': array([0.05113465, 0.05072721, 0.09231273, 0.05902809, 0.05051832,
       0.09231273, 0.05277216, 0.05072721, 0.05445859, 0.09599276,
       0.04640082, 0.05445859, 0.07934066, 0.05072721, 0.03841452,
       0.10215843, 0.06746381, 0.03841452, 0.08447771, 0.05072721,
       0.03755038, 0.10211966, 0.40272749, 0.03755038, 0.08508648,
       0.05072721, 0.01675697, 0.10184938, 0.93802992, 0.01675697]), 'rank_test_score': array([16, 17, 11, 15, 22, 11, 13, 17,  7, 25, 23,  7, 14, 17,  3, 27, 28,
        3, 10, 17,  1, 26, 29,  1,  9, 17,  5, 24, 30,  5], dtype=int32)}

In [10]:
grid_pred = grid.predict(X_test)

In [11]:
from sklearn.metrics import r2_score
r_score = r2_score(y_test,grid_pred)
print("The r_score value of best parameter {}:".format(grid.best_params_), r_score)

The r_score value of best parameter {'C': 2000, 'gamma': 'auto', 'kernel': 'linear'}: 0.6893263105100382

In [12]:
grid.predict([[54,34,2,1,1]])

C:\Anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but SVR was fitted with feature names
  warnings.warn(

array([29926.92228142])

In [15]:
#Convert keyvalue pair (Dict variable in to tablur form (dataframe))
table = pd.DataFrame.from_dict(result)

In [16]:
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_C,param_gamma,param_kernel,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.160295,0.021491,0.051145,0.006776,10,auto,rbf,"{'C': 10, 'gamma': 'auto', 'kernel': 'rbf'}",-0.041899,-0.035931,-0.147151,-0.139987,-0.142206,-0.101435,0.051135,16
1,0.088500,0.005823,0.023521,0.004424,10,auto,sigmoid,"{'C': 10, 'gamma': 'auto', 'kernel': 'sigmoid'}",-0.041634,-0.038077,-0.148674,-0.138698,-0.142137,-0.101844,0.050727,17
2,0.126377,0.008268,0.023639,0.002187,10,auto,linear,"{'C': 10, 'gamma': 'auto', 'kernel': 'linear'}",-0.099849,0.109498,-0.136196,-0.141381,-0.075432,-0.068672,0.092313,11
3,0.124153,0.006738,0.048599,0.003526,10,scale,rbf,"{'C': 10, 'gamma': 'scale', 'kernel': 'rbf'}",-0.045477,-0.013336,-0.151791,-0.151967,-0.139448,-0.100404,0.059028,15
4,0.136777,0.002869,0.033138,0.002981,10,scale,sigmoid,"{'C': 10, 'gamma': 'scale', 'kernel': 'sigmoid'}",-0.042877,-0.039512,-0.150154,-0.138492,-0.143396,-0.102886,0.050518,22
5,0.112469,0.006689,0.017422,0.002841,10,scale,linear,"{'C': 10, 'gamma': 'scale', 'kernel': 'linear'}",-0.099849,0.109498,-0.136196,-0.141381,-0.075432,-0.068672,0.092313,11
6,0.162978,0.012503,0.044816,0.002216,100,auto,rbf,"{'C': 100, 'gamma': 'auto', 'kernel': 'rbf'}",-0.040107,-0.020972,-0.140683,-0.137931,-0.133749,-0.094689,0.052772,13
7,0.087157,0.007671,0.019552,0.001935,100,auto,sigmoid,"{'C': 100, 'gamma': 'auto', 'kernel': 'sigmoid'}",-0.041634,-0.038077,-0.148674,-0.138698,-0.142137,-0.101844,0.050727,17
8,0.210187,0.042722,0.015812,0.001101,100,auto,linear,"{'C': 100, 'gamma': 'auto', 'kernel': 'linear'}",0.477795,0.582292,0.432079,0.458983,0.439511,0.478132,0.054459,7
9,0.113970,0.004610,0.047849,0.005691,100,scale,rbf,"{'C': 100, 'gamma': 'scale', 'kernel': 'rbf'}",-0.158546,0.013775,-0.243127,-0.254520,-0.166782,-0.161840,0.095993,25
10,0.133355,0.004446,0.032819,0.000857,100,scale,sigmoid,"{'C': 100, 'gamma': 'scale', 'kernel': 'sigmoid'}",-0.059561,-0.063480,-0.155368,-0.152757,-0.160115,-0.118256,0.046401,23
11,0.216651,0.044591,0.018854,0.001256,100,scale,linear,"{'C': 100, 'gamma': 'scale', 'kernel': 'linear'}",0.477795,0.582292,0.432079,0.458983,0.439511,0.478132,0.054459,7
12,0.233017,0.008271,0.049359,0.002918,1000,auto,rbf,"{'C': 1000, 'gamma': 'auto', 'kernel': 'rbf'}",-0.064434,0.041169,-0.173627,-0.162395,-0.131375,-0.098133,0.079341,14
13,0.079167,0.010165,0.020520,0.002123,1000,auto,sigmoid,"{'C': 1000, 'gamma': 'auto', 'kernel': 'sigmoid'}",-0.041634,-0.038077,-0.148674,-0.138698,-0.142137,-0.101844,0.050727,17
14,0.747055,0.075733,0.021001,0.002926,1000,auto,linear,"{'C': 1000, 'gamma': 'auto', 'kernel': 'linear'}",0.592288,0.663607,0.559347,0.582636,0.558849,0.591345,0.038415,3
15,0.133450,0.005097,0.051582,0.001362,1000,scale,rbf,"{'C': 1000, 'gamma': 'scale', 'kernel': 'rbf'}",-0.191422,0.021962,-0.246590,-0.264813,-0.174935,-0.171160,0.102158,27
16,0.137458,0.006464,0.031437,0.001517,1000,scale,sigmoid,"{'C': 1000, 'gamma': 'scale', 'kernel': 'sigmo...",-1.141295,-1.269703,-1.074688,-1.221982,-1.154634,-1.172460,0.067464,28
17,0.763179,0.066125,0.018603,0.002374,1000,scale,linear,"{'C': 1000, 'gamma': 'scale', 'kernel': 'linear'}",0.592288,0.663607,0.559347,0.582636,0.558849,0.591345,0.038415,3
18,0.284499,0.017634,0.051494,0.002619,2000,auto,rbf,"{'C': 2000, 'gamma': 'auto', 'kernel': 'rbf'}",-0.041473,0.086956,-0.143583,-0.129675,-0.106186,-0.066792,0.084478,10
19,0.083638,0.002948,0.019598,0.001290,2000,auto,sigmoid,"{'C': 2000, 'gamma': 'auto', 'kernel': 'sigmoid'}",-0.041634,-0.038077,-0.148674,-0.138698,-0.142137,-0.101844,0.050727,17
20,1.314015,0.149666,0.018683,0.001045,2000,auto,linear,"{'C': 2000, 'gamma': 'auto', 'kernel': 'linear'}",0.600340,0.664454,0.564693,0.618692,0.563567,0.602349,0.037550,1
21,0.144461,0.009356,0.048507,0.004964,2000,scale,rbf,"{'C': 2000, 'gamma': 'scale', 'kernel': 'rbf'}",-0.188138,0.029758,-0.237425,-0.256760,-0.168701,-0.164253,0.102120,26
22,0.138898,0.003068,0.032181,0.001213,2000,scale,sigmoid,"{'C': 2000, 'gamma': 'scale', 'kernel': 'sigmo...",-4.204699,-4.639898,-3.600431,-4.265575,-3.612375,-4.064596,0.402727,29
23,1.315939,0.160276,0.019490,0.001158,2000,scale,linear,"{'C': 2000, 'gamma': 'scale', 'kernel': 'linear'}",0.600340,0.664454,0.564693,0.618692,0.563567,0.602349,0.037550,1
24,0.360427,0.043621,0.051778,0.002705,3000,auto,rbf,"{'C': 3000, 'gamma': 'auto', 'kernel': 'rbf'}",-0.010838,0.123650,-0.111710,-0.089701,-0.074932,-0.032706,0.085086,9
25,0.087135,0.005328,0.020848,0.002321,3000,auto,sigmoid,"{'C': 3000, 'gamma': 'auto', 'kernel': 'sigmoid'}",-0.041634,-0.038077,-0.148674,-0.138698,-0.142137,-0.101844,0.050727,17
26,2.509637,1.059856,0.016384,0.004633,3000,auto,linear,"{'C': 3000, 'gamma': 'auto', 'kernel': 'linear'}",0.600282,0.600528,0.571175,0.562946,0.565766,0.580139,0.016757,5
27,0.144658,0.003692,0.049978,0.003683,3000,scale,rbf,"{'C': 3000, 'gamma': 'scale', 'kernel': 'rbf'}",-0.182267,0.038588,-0.228062,-0.245915,-0.161880,-0.155907,0.101849,24
28,0.144763,0.004922,0.036134,0.003185,3000,scale,sigmoid,"{'C': 3000, 'gamma': 'scale', 'kernel': 'sigmo...",-9.347820,-10.015654,-7.896694,-9.548932,-7.664412,-8.894703,0.938030,30
29,2.141991,0.925656,0.011168,0.003277,3000,scale,linear,"{'C': 3000, 'gamma': 'scale', 'kernel': 'linear'}",0.600282,0.600528,0.571175,0.562946,0.565766,0.580139,0.016757,5