In [1]:
import pandas as pd
dataset = pd.read_csv("insurance_pre.csv")

In [2]:
dataset.head(2)

   age     sex    bmi  children smoker     charges
0   19  female  27.90         0    yes  16884.9240
1   18    male  33.77         1     no   1725.5523

In [3]:
dataset = pd.get_dummies(dataset, dtype=int, drop_first=True)

In [4]:
dataset.head(2)

   age    bmi  children     charges  sex_male  smoker_yes
0   19  27.90         0  16884.9240         0           1
1   18  33.77         1   1725.5523         1           0

In [ ]:
dataset.columns

In [5]:
independent=dataset[['age', 'bmi', 'children',  'sex_male', 'smoker_yes']]
dependent=dataset[['charges']]

In [6]:
#from sklearn.model_selection import train_test_split
#X_train, X_test, y_train, y_test = train_test_split(independent, dependent, test_size=0.3, random_state=0)

In [7]:
from sklearn.model_selection import GridSearchCV
from sklearn.svm import SVR
param_grid = {'kernel':['rbf','sigmoid','linear'], 
              'C':[10,100,1000,2000,3000], 'gamma':['auto','scale']}
grid = GridSearchCV(SVR(), param_grid, refit=True, verbose=3, n_jobs=-1)
grid.fit(independent, dependent)

Fitting 5 folds for each of 30 candidates, totalling 150 fits

C:\Anaconda3\Lib\site-packages\sklearn\utils\validation.py:1406: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

GridSearchCV(estimator=SVR(), n_jobs=-1,
             param_grid={'C': [10, 100, 1000, 2000, 3000],
                         'gamma': ['auto', 'scale'],
                         'kernel': ['rbf', 'sigmoid', 'linear']},
             verbose=3)

In [8]:
result=grid.cv_results_
print(result)

{'mean_fit_time': array([0.34203587, 0.17221513, 0.20193844, 0.2483645 , 0.27751422,
       0.19839721, 0.33488607, 0.17088594, 0.39197154, 0.24218822,
       0.27804418, 0.39707642, 0.46344604, 0.17881236, 1.32220025,
       0.26420708, 0.27416844, 1.31087976, 0.63903613, 0.17385397,
       2.13716769, 0.27254138, 0.27962785, 2.15251055, 0.74181871,
       0.17585788, 3.84843717, 0.26847081, 0.28167663, 2.99397817]), 'std_fit_time': array([0.02352413, 0.0106713 , 0.00853817, 0.00756631, 0.0103992 ,
       0.00715188, 0.00684951, 0.01653647, 0.0165253 , 0.00756148,
       0.00842281, 0.01863733, 0.01053068, 0.00871337, 0.12629039,
       0.0073085 , 0.00709099, 0.1475608 , 0.03257812, 0.00740569,
       0.1357298 , 0.00596464, 0.00585633, 0.13262073, 0.04009788,
       0.0052266 , 0.61237816, 0.00693326, 0.00461132, 0.45386296]), 'mean_score_time': array([0.0812809 , 0.03374996, 0.03244233, 0.09445081, 0.05843358,
       0.03166175, 0.09125218, 0.03298397, 0.02901983, 0.09466119,
       0.06314526, 0.03410163, 0.09518747, 0.03540525, 0.0313334 ,
       0.09426637, 0.05955815, 0.03188162, 0.09651237, 0.03500509,
       0.03154492, 0.09693189, 0.0599278 , 0.03228002, 0.09517117,
       0.03495107, 0.02726097, 0.09474955, 0.05843024, 0.01756849]), 'std_score_time': array([0.0057279 , 0.00105396, 0.00268082, 0.00438263, 0.00484707,
       0.00423725, 0.00385287, 0.00277658, 0.00209627, 0.00236929,
       0.00240156, 0.0024377 , 0.00412524, 0.00437781, 0.00224577,
       0.00327497, 0.0027878 , 0.00086352, 0.0037699 , 0.00110239,
       0.00215625, 0.0015918 , 0.00254734, 0.00202862, 0.00414506,
       0.00127043, 0.00691656, 0.0031279 , 0.00249923, 0.0027616 ]), 'param_C': masked_array(data=[10, 10, 10, 10, 10, 10, 100, 100, 100, 100, 100, 100,
                   1000, 1000, 1000, 1000, 1000, 1000, 2000, 2000, 2000,
                   2000, 2000, 2000, 3000, 3000, 3000, 3000, 3000, 3000],
             mask=[False, False, False, False, False, False, False, False,
                   False, False, False, False, False, False, False, False,
                   False, False, False, False, False, False, False, False,
                   False, False, False, False, False, False],
       fill_value=999999), 'param_gamma': masked_array(data=['auto', 'auto', 'auto', 'scale', 'scale', 'scale',
                   'auto', 'auto', 'auto', 'scale', 'scale', 'scale',
                   'auto', 'auto', 'auto', 'scale', 'scale', 'scale',
                   'auto', 'auto', 'auto', 'scale', 'scale', 'scale',
                   'auto', 'auto', 'auto', 'scale', 'scale', 'scale'],
             mask=[False, False, False, False, False, False, False, False,
                   False, False, False, False, False, False, False, False,
                   False, False, False, False, False, False, False, False,
                   False, False, False, False, False, False],
       fill_value=np.str_('?'),
            dtype=object), 'param_kernel': masked_array(data=['rbf', 'sigmoid', 'linear', 'rbf', 'sigmoid', 'linear',
                   'rbf', 'sigmoid', 'linear', 'rbf', 'sigmoid', 'linear',
                   'rbf', 'sigmoid', 'linear', 'rbf', 'sigmoid', 'linear',
                   'rbf', 'sigmoid', 'linear', 'rbf', 'sigmoid', 'linear',
                   'rbf', 'sigmoid', 'linear', 'rbf', 'sigmoid', 'linear'],
             mask=[False, False, False, False, False, False, False, False,
                   False, False, False, False, False, False, False, False,
                   False, False, False, False, False, False, False, False,
                   False, False, False, False, False, False],
       fill_value=np.str_('?'),
            dtype=object), 'params': [{'C': 10, 'gamma': 'auto', 'kernel': 'rbf'}, {'C': 10, 'gamma': 'auto', 'kernel': 'sigmoid'}, {'C': 10, 'gamma': 'auto', 'kernel': 'linear'}, {'C': 10, 'gamma': 'scale', 'kernel': 'rbf'}, {'C': 10, 'gamma': 'scale', 'kernel': 'sigmoid'}, {'C': 10, 'gamma': 'scale', 'kernel': 'linear'}, {'C': 100, 'gamma': 'auto', 'kernel': 'rbf'}, {'C': 100, 'gamma': 'auto', 'kernel': 'sigmoid'}, {'C': 100, 'gamma': 'auto', 'kernel': 'linear'}, {'C': 100, 'gamma': 'scale', 'kernel': 'rbf'}, {'C': 100, 'gamma': 'scale', 'kernel': 'sigmoid'}, {'C': 100, 'gamma': 'scale', 'kernel': 'linear'}, {'C': 1000, 'gamma': 'auto', 'kernel': 'rbf'}, {'C': 1000, 'gamma': 'auto', 'kernel': 'sigmoid'}, {'C': 1000, 'gamma': 'auto', 'kernel': 'linear'}, {'C': 1000, 'gamma': 'scale', 'kernel': 'rbf'}, {'C': 1000, 'gamma': 'scale', 'kernel': 'sigmoid'}, {'C': 1000, 'gamma': 'scale', 'kernel': 'linear'}, {'C': 2000, 'gamma': 'auto', 'kernel': 'rbf'}, {'C': 2000, 'gamma': 'auto', 'kernel': 'sigmoid'}, {'C': 2000, 'gamma': 'auto', 'kernel': 'linear'}, {'C': 2000, 'gamma': 'scale', 'kernel': 'rbf'}, {'C': 2000, 'gamma': 'scale', 'kernel': 'sigmoid'}, {'C': 2000, 'gamma': 'scale', 'kernel': 'linear'}, {'C': 3000, 'gamma': 'auto', 'kernel': 'rbf'}, {'C': 3000, 'gamma': 'auto', 'kernel': 'sigmoid'}, {'C': 3000, 'gamma': 'auto', 'kernel': 'linear'}, {'C': 3000, 'gamma': 'scale', 'kernel': 'rbf'}, {'C': 3000, 'gamma': 'scale', 'kernel': 'sigmoid'}, {'C': 3000, 'gamma': 'scale', 'kernel': 'linear'}], 'split0_test_score': array([-1.13791418e-01, -1.15327869e-01, -1.89428955e-02, -1.10409129e-01,
       -1.16743240e-01, -1.89428955e-02, -1.00011641e-01, -1.15327869e-01,
        5.59312970e-01, -1.60181719e-01, -1.42454969e-01,  5.59312970e-01,
       -8.06915978e-02, -1.15327869e-01,  7.36398496e-01, -1.55430287e-01,
       -2.04313994e+00,  7.36398496e-01, -3.31261632e-02, -1.15327869e-01,
        6.82349148e-01, -1.43509703e-01, -7.20931696e+00,  6.82349148e-01,
        1.17409262e-02, -1.15327869e-01,  6.77778294e-01, -1.28958340e-01,
       -1.55618534e+01,  6.77778294e-01]), 'split1_test_score': array([-1.10741021e-01, -1.13567480e-01,  2.98864671e-02, -9.74588632e-02,
       -1.19311574e-01,  2.98864671e-02, -9.84564259e-02, -1.13567480e-01,
        5.21797761e-01, -1.07253108e-01, -1.60830654e-01,  5.21797761e-01,
       -5.43468783e-02, -1.13567480e-01,  6.75161795e-01, -9.82665598e-02,
       -2.68612062e+00,  6.75161795e-01, -2.83525677e-03, -1.13567480e-01,
        6.30641615e-01, -8.75949754e-02, -9.28294011e+00,  6.30641615e-01,
        4.36594992e-02, -1.13567480e-01,  6.26814291e-01, -7.55781929e-02,
       -2.04989082e+01,  6.26814291e-01]), 'split2_test_score': array([-7.91562856e-02, -8.16081846e-02,  2.21674226e-02, -7.44875522e-02,
       -8.52138486e-02,  2.21674226e-02, -7.29810803e-02, -8.16081846e-02,
        5.47690802e-01, -1.23430337e-01, -1.17544297e-01,  5.47690802e-01,
       -6.28764896e-02, -8.16081846e-02,  6.80002381e-01, -1.23723557e-01,
       -2.19456334e+00,  6.80002381e-01, -2.65445159e-02, -8.16081846e-02,
        7.50713567e-01, -1.13312371e-01, -7.77657753e+00,  7.50713567e-01,
        1.33830349e-02, -8.16081846e-02,  7.32805738e-01, -1.00198784e-01,
       -1.70954740e+01,  7.32805738e-01]), 'split3_test_score': array([-1.03389045e-01, -1.06066720e-01,  3.11150946e-03, -9.95972567e-02,
       -1.08210107e-01,  3.11150946e-03, -9.66153848e-02, -1.06066720e-01,
        5.38804573e-01, -1.37753025e-01, -1.37983588e-01,  5.38804573e-01,
       -7.93289125e-02, -1.06066720e-01,  6.99376769e-01, -1.37136880e-01,
       -2.21085823e+00,  6.99376769e-01, -2.91402441e-02, -1.06066720e-01,
        6.46367540e-01, -1.28590699e-01, -7.74507386e+00,  6.46367540e-01,
        2.16943418e-02, -1.06066720e-01,  6.33478783e-01, -1.16051182e-01,
       -1.67508766e+01,  6.33478783e-01]), 'split4_test_score': array([-1.06488205e-01, -1.07195462e-01, -6.66534824e-02, -1.24428187e-01,
       -1.08716360e-01, -6.66534824e-02, -1.02231960e-01, -1.07195462e-01,
        5.08517616e-01, -2.09551109e-01, -1.30401931e-01,  5.08517616e-01,
       -1.17983058e-01, -1.07195462e-01,  6.77951606e-01, -2.06405243e-01,
       -1.94252105e+00,  6.77951606e-01, -6.73921389e-02, -1.07195462e-01,
        7.22260926e-01, -1.93991530e-01, -6.89171908e+00,  7.22260926e-01,
       -1.29484814e-02, -1.07195462e-01,  6.98691627e-01, -1.79304093e-01,
       -1.50121676e+01,  6.98691627e-01]), 'mean_test_score': array([-1.02713195e-01, -1.04753143e-01, -6.08619573e-03, -1.01276198e-01,
       -1.07639026e-01, -6.08619573e-03, -9.40592985e-02, -1.04753143e-01,
        5.35224744e-01, -1.47633859e-01, -1.37843088e-01,  5.35224744e-01,
       -7.90453873e-02, -1.04753143e-01,  6.93778210e-01, -1.44192505e-01,
       -2.21544064e+00,  6.93778210e-01, -3.18076638e-02, -1.04753143e-01,
        6.86466559e-01, -1.33399856e-01, -7.78112551e+00,  6.86466559e-01,
        1.55058641e-02, -1.04753143e-01,  6.73913747e-01, -1.20018118e-01,
       -1.69838559e+01,  6.73913747e-01]), 'std_test_score': array([0.01230291, 0.012107  , 0.03467157, 0.01645872, 0.01202922,
       0.03467157, 0.01069937, 0.012107  , 0.01812189, 0.03551124,
       0.01426274, 0.01812189, 0.02186496, 0.012107  , 0.02295499,
       0.036262  , 0.25540914, 0.02295499, 0.02069884, 0.012107  ,
       0.04505602, 0.03549164, 0.82155661, 0.04505602, 0.01821678,
       0.012107  , 0.03987603, 0.03457804, 1.91478335, 0.03987603]), 'rank_test_score': array([16, 17, 10, 15, 22, 10, 14, 17,  7, 27, 25,  7, 13, 17,  1, 26, 28,
        1, 12, 17,  3, 24, 29,  3,  9, 17,  5, 23, 30,  5], dtype=int32)}

In [12]:
#from sklearn.metrics import r2_score
#r_score = r2_score(y_test,grid_pred)
#print("The r_score value of best parameter {}:".format(grid.best_params_), r_score)
print("The best parameter is {}:".format(grid.best_params_))

The best parameter is {'C': 1000, 'gamma': 'auto', 'kernel': 'linear'}:

In [15]:
grid.predict([[54,34,2,1,1]])

C:\Anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but SVR was fitted with feature names
  warnings.warn(

array([35797.84859613])

In [18]:
table = pd.DataFrame.from_dict(result)

In [19]:
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_C,param_gamma,param_kernel,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.342036,0.023524,0.081281,0.005728,10,auto,rbf,"{'C': 10, 'gamma': 'auto', 'kernel': 'rbf'}",-0.113791,-0.110741,-0.079156,-0.103389,-0.106488,-0.102713,0.012303,16
1,0.172215,0.010671,0.033750,0.001054,10,auto,sigmoid,"{'C': 10, 'gamma': 'auto', 'kernel': 'sigmoid'}",-0.115328,-0.113567,-0.081608,-0.106067,-0.107195,-0.104753,0.012107,17
2,0.201938,0.008538,0.032442,0.002681,10,auto,linear,"{'C': 10, 'gamma': 'auto', 'kernel': 'linear'}",-0.018943,0.029886,0.022167,0.003112,-0.066653,-0.006086,0.034672,10
3,0.248364,0.007566,0.094451,0.004383,10,scale,rbf,"{'C': 10, 'gamma': 'scale', 'kernel': 'rbf'}",-0.110409,-0.097459,-0.074488,-0.099597,-0.124428,-0.101276,0.016459,15
4,0.277514,0.010399,0.058434,0.004847,10,scale,sigmoid,"{'C': 10, 'gamma': 'scale', 'kernel': 'sigmoid'}",-0.116743,-0.119312,-0.085214,-0.108210,-0.108716,-0.107639,0.012029,22
5,0.198397,0.007152,0.031662,0.004237,10,scale,linear,"{'C': 10, 'gamma': 'scale', 'kernel': 'linear'}",-0.018943,0.029886,0.022167,0.003112,-0.066653,-0.006086,0.034672,10
6,0.334886,0.006850,0.091252,0.003853,100,auto,rbf,"{'C': 100, 'gamma': 'auto', 'kernel': 'rbf'}",-0.100012,-0.098456,-0.072981,-0.096615,-0.102232,-0.094059,0.010699,14
7,0.170886,0.016536,0.032984,0.002777,100,auto,sigmoid,"{'C': 100, 'gamma': 'auto', 'kernel': 'sigmoid'}",-0.115328,-0.113567,-0.081608,-0.106067,-0.107195,-0.104753,0.012107,17
8,0.391972,0.016525,0.029020,0.002096,100,auto,linear,"{'C': 100, 'gamma': 'auto', 'kernel': 'linear'}",0.559313,0.521798,0.547691,0.538805,0.508518,0.535225,0.018122,7
9,0.242188,0.007561,0.094661,0.002369,100,scale,rbf,"{'C': 100, 'gamma': 'scale', 'kernel': 'rbf'}",-0.160182,-0.107253,-0.123430,-0.137753,-0.209551,-0.147634,0.035511,27
10,0.278044,0.008423,0.063145,0.002402,100,scale,sigmoid,"{'C': 100, 'gamma': 'scale', 'kernel': 'sigmoid'}",-0.142455,-0.160831,-0.117544,-0.137984,-0.130402,-0.137843,0.014263,25
11,0.397076,0.018637,0.034102,0.002438,100,scale,linear,"{'C': 100, 'gamma': 'scale', 'kernel': 'linear'}",0.559313,0.521798,0.547691,0.538805,0.508518,0.535225,0.018122,7
12,0.463446,0.010531,0.095187,0.004125,1000,auto,rbf,"{'C': 1000, 'gamma': 'auto', 'kernel': 'rbf'}",-0.080692,-0.054347,-0.062876,-0.079329,-0.117983,-0.079045,0.021865,13
13,0.178812,0.008713,0.035405,0.004378,1000,auto,sigmoid,"{'C': 1000, 'gamma': 'auto', 'kernel': 'sigmoid'}",-0.115328,-0.113567,-0.081608,-0.106067,-0.107195,-0.104753,0.012107,17
14,1.322200,0.126290,0.031333,0.002246,1000,auto,linear,"{'C': 1000, 'gamma': 'auto', 'kernel': 'linear'}",0.736398,0.675162,0.680002,0.699377,0.677952,0.693778,0.022955,1
15,0.264207,0.007308,0.094266,0.003275,1000,scale,rbf,"{'C': 1000, 'gamma': 'scale', 'kernel': 'rbf'}",-0.155430,-0.098267,-0.123724,-0.137137,-0.206405,-0.144193,0.036262,26
16,0.274168,0.007091,0.059558,0.002788,1000,scale,sigmoid,"{'C': 1000, 'gamma': 'scale', 'kernel': 'sigmo...",-2.043140,-2.686121,-2.194563,-2.210858,-1.942521,-2.215441,0.255409,28
17,1.310880,0.147561,0.031882,0.000864,1000,scale,linear,"{'C': 1000, 'gamma': 'scale', 'kernel': 'linear'}",0.736398,0.675162,0.680002,0.699377,0.677952,0.693778,0.022955,1
18,0.639036,0.032578,0.096512,0.003770,2000,auto,rbf,"{'C': 2000, 'gamma': 'auto', 'kernel': 'rbf'}",-0.033126,-0.002835,-0.026545,-0.029140,-0.067392,-0.031808,0.020699,12
19,0.173854,0.007406,0.035005,0.001102,2000,auto,sigmoid,"{'C': 2000, 'gamma': 'auto', 'kernel': 'sigmoid'}",-0.115328,-0.113567,-0.081608,-0.106067,-0.107195,-0.104753,0.012107,17
20,2.137168,0.135730,0.031545,0.002156,2000,auto,linear,"{'C': 2000, 'gamma': 'auto', 'kernel': 'linear'}",0.682349,0.630642,0.750714,0.646368,0.722261,0.686467,0.045056,3
21,0.272541,0.005965,0.096932,0.001592,2000,scale,rbf,"{'C': 2000, 'gamma': 'scale', 'kernel': 'rbf'}",-0.143510,-0.087595,-0.113312,-0.128591,-0.193992,-0.133400,0.035492,24
22,0.279628,0.005856,0.059928,0.002547,2000,scale,sigmoid,"{'C': 2000, 'gamma': 'scale', 'kernel': 'sigmo...",-7.209317,-9.282940,-7.776578,-7.745074,-6.891719,-7.781126,0.821557,29
23,2.152511,0.132621,0.032280,0.002029,2000,scale,linear,"{'C': 2000, 'gamma': 'scale', 'kernel': 'linear'}",0.682349,0.630642,0.750714,0.646368,0.722261,0.686467,0.045056,3
24,0.741819,0.040098,0.095171,0.004145,3000,auto,rbf,"{'C': 3000, 'gamma': 'auto', 'kernel': 'rbf'}",0.011741,0.043659,0.013383,0.021694,-0.012948,0.015506,0.018217,9
25,0.175858,0.005227,0.034951,0.001270,3000,auto,sigmoid,"{'C': 3000, 'gamma': 'auto', 'kernel': 'sigmoid'}",-0.115328,-0.113567,-0.081608,-0.106067,-0.107195,-0.104753,0.012107,17
26,3.848437,0.612378,0.027261,0.006917,3000,auto,linear,"{'C': 3000, 'gamma': 'auto', 'kernel': 'linear'}",0.677778,0.626814,0.732806,0.633479,0.698692,0.673914,0.039876,5
27,0.268471,0.006933,0.094750,0.003128,3000,scale,rbf,"{'C': 3000, 'gamma': 'scale', 'kernel': 'rbf'}",-0.128958,-0.075578,-0.100199,-0.116051,-0.179304,-0.120018,0.034578,23
28,0.281677,0.004611,0.058430,0.002499,3000,scale,sigmoid,"{'C': 3000, 'gamma': 'scale', 'kernel': 'sigmo...",-15.561853,-20.498908,-17.095474,-16.750877,-15.012168,-16.983856,1.914783,30
29,2.993978,0.453863,0.017568,0.002762,3000,scale,linear,"{'C': 3000, 'gamma': 'scale', 'kernel': 'linear'}",0.677778,0.626814,0.732806,0.633479,0.698692,0.673914,0.039876,5